// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_List from "rescript/lib/es6/belt_List.js";

import './BalanceDisplay.css';
;

function BalanceDisplay(props) {
  var expenses = props.expenses;
  var totalIncome = Belt_List.reduce(Belt_List.keep(expenses, (function (exp) {
              return exp.expType === /* Income */0;
            })), 0.0, (function (acc, item) {
          return acc + item.amount;
        }));
  var totalExpense = Belt_List.reduce(Belt_List.keep(expenses, (function (exp) {
              return exp.expType === /* Expense */1;
            })), 0.0, (function (acc, item) {
          return acc + item.amount;
        }));
  return React.createElement("div", {
              className: "balanceContainer"
            }, React.createElement("p", {
                  className: "balanceTitle"
                }, "Your Balance"), React.createElement("p", {
                  className: "balanceValue"
                }, "$", totalExpense > totalIncome ? "-" : "", (
                    totalExpense > totalIncome ? totalExpense - totalIncome : totalIncome - totalExpense
                  ).toString()), React.createElement("div", {
                  className: "balanceDashboard"
                }, React.createElement("div", {
                      className: "incomeData"
                    }, React.createElement("p", {
                          className: "dashboardLabel"
                        }, "Income"), React.createElement("p", {
                          className: "dashboardValue"
                        }, "$", totalIncome)), React.createElement("div", {
                      className: "expenseData"
                    }, React.createElement("p", {
                          className: "dashboardLabel"
                        }, "Expense"), React.createElement("p", {
                          className: "dashboardValue"
                        }, "$", totalExpense))));
}

var make = BalanceDisplay;

export {
  make ,
}
/*  Not a pure module */
