// Generated by ReScript, PLEASE EDIT WITH CARE


var addTransactionLabel = "Add new transaction";

var balanceDashboard = "Your Balance";

var incomeLabel = "Income";

var expenseLabel = "Expense";

var historyLabel = "History";

var headerLabel = "Expense Tracker";

var addTextInputLabel = "Text";

var addAmountInputLabel = "Amount";

var addAmountInputInfo = "(negative - expense, positive - income)";

export {
  addTransactionLabel ,
  balanceDashboard ,
  incomeLabel ,
  expenseLabel ,
  historyLabel ,
  headerLabel ,
  addTextInputLabel ,
  addAmountInputLabel ,
  addAmountInputInfo ,
}
/* No side effect */
