// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Store from "../../utils/Store.bs.js";
import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

import './AddTransaction.css'
;

function AddTransaction(props) {
  var setExpenses = props.setExpenses;
  var match = React.useState(function () {
        return "";
      });
  var setTitle = match[1];
  var title = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setText = match$1[1];
  var text = match$1[0];
  var onAmountChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    Curry._1(setText, (function (param) {
            return value;
          }));
  };
  var onTitleChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    Curry._1(setTitle, (function (param) {
            return value;
          }));
  };
  var onClick = function (evt) {
    evt.preventDefault();
    var amount = Belt_Option.getWithDefault(Belt_Float.fromString(text), 0.0);
    Curry._1(setExpenses, (function (prev) {
            return Belt_List.add(prev, {
                        id: Js_math.random_int(1, 999),
                        title: title,
                        amount: amount > 0.0 ? amount : amount * -1.0,
                        expType: amount > 0.0 ? /* Income */0 : /* Expense */1
                      });
          }));
    Curry._1(setText, (function (param) {
            return "";
          }));
    Curry._1(setTitle, (function (param) {
            return "";
          }));
  };
  return React.createElement("div", {
              className: "transactionContainer"
            }, React.createElement("div", {
                  className: "transactionLabel"
                }, React.createElement("p", undefined, Store.addTransactionLabel)), React.createElement("div", {
                  className: "inputContainer"
                }, React.createElement("p", undefined, Store.addTextInputLabel), React.createElement("input", {
                      placeholder: "Enter text...",
                      value: title,
                      onChange: onTitleChange
                    })), React.createElement("div", {
                  className: "inputContainer"
                }, React.createElement("p", undefined, Store.addAmountInputLabel), React.createElement("p", undefined, Store.addAmountInputLabel), React.createElement("input", {
                      placeholder: "Enter amount...",
                      value: text,
                      onChange: onAmountChange
                    })), React.createElement("button", {
                  className: "submitBtn",
                  onClick: onClick
                }, "Add transaction"));
}

var make = AddTransaction;

export {
  make ,
}
/*  Not a pure module */
