// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header from "./components/Header/Header.bs.js";
import * as AddTransaction from "./components/AddTransaction/AddTransaction.bs.js";
import * as BalanceDisplay from "./components/BalanceDisplay/BalanceDisplay.bs.js";
import * as ExpenseHistory from "./components/ExpenseHistory/ExpenseHistory.bs.js";

import './App.css';
;

function App(props) {
  var match = React.useState(function () {
        return /* [] */0;
      });
  var expenses = match[0];
  return React.createElement("div", {
              className: "App"
            }, React.createElement(Header.make, {}), React.createElement(BalanceDisplay.make, {
                  expenses: expenses
                }), React.createElement(ExpenseHistory.make, {
                  expenses: expenses
                }), React.createElement(AddTransaction.make, {
                  setExpenses: match[1]
                }));
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
